### ISSUE TITLE
Stream Memory Fix

### ISSUE THREAD

**Issue by anonymous64** [Whitetigerswt/gtasa_crashfix#15]
How about adding Stream Memory Fix as an optional setting? (when the 128mb limit is reached there's lower FPS than if it wasn't reached)

http://dev-c.com/gtasa   ---> Stream Memory Fix

**Comment by Whitetigerswt** [comment]
Since this has been added in SA-MP 0.3.7, is this still necessary?

**Comment by anonymous64** [comment]
Nope.
