### ISSUE TITLE
Alt tab cursor stuck

### ISSUE THREAD

**Issue by Whitetigerswt** [Whitetigerswt/gtasa_crashfix#18]
When you alt tab, the cursor gets stuck in the corner sometimes. This is fixed in ACv2 and can just be copied here.

**Comment by oscar-broman** [comment]
Fucks up in window mode sometimes. Can't press anything or move the mouse.

**Comment by oscar-broman** [comment]
That issue with keys/mouse not working happens even without crashes.

**Comment by Whitetigerswt** [comment]
But it shouldn't happen with it?

**Comment by oscar-broman** [comment]
I mean I thought the fix for this caused the issue with window mode, but it's unrelated.
