### ISSUE TITLE
Weird vehicle handling when high FPS

### ISSUE THREAD

**Issue by ikkentim** [Whitetigerswt/gtasa_crashfix#20]
The following things occur when my FPS limiter is off:
- All cars break real quickly when I release the forward button
- All cars have a hard time steering
- If the car I sit in stands still for a little while, they start shaking

Info:
- Using latest SA-MP client
- FPS is 565
- No other mods

When my FPS goes low again (eg when I wanted to record the symptoms) all's OK again.

Don't know if you want to fix this, but I thought you'd like to know.

**Comment by Whitetigerswt** [comment]
Yeah, it's important to note that this is a problem with gta sa itself, and there are a number of things you won't be able to do at high fps  ( http://pcgamingwiki.com/wiki/Grand_Theft_Auto:_San_Andreas#Timing-related_issues). I don't know if it's even worth attempting to fix an issue as big as this. It's really beyond the scope of this mod and even if I could fix it, it most likely would cause even more glaring issues in samp
