### ISSUE TITLE
Latest version crashing with SA:MP

### ISSUE THREAD

**Issue by ESzn** [Whitetigerswt/gtasa_crashfix#22]
Crashes when it starts loading. Only Cleo 4.3 and Reload.cs installed.
Version 2.3.1 works fine.

**Comment by Whitetigerswt** [comment]
Are you using 0.3.7?

**Comment by ESzn** [comment]
Yes.

**Comment by eXeGOODER** [comment]
I put crashes.asi 2.4 - game crash. Install crashes-v2.4.exe - all good.

**Comment by Whitetigerswt** [comment]
Does it work in 0.3z @ESzn

**Comment by Whitetigerswt** [comment]
@eXeGOODER then use the installer, what's the problem?

**Comment by ESzn** [comment]
@Whitetigerswt i just tested it, it's still not working either with crashes.asi or using the installer.

**Comment by Whitetigerswt** [comment]
Does it work in 0.3z

**Comment by ESzn** [comment]
No it doesn't

**Comment by eXeGOODER** [comment]
@Whitetigerswt no problem, SA-MP 0.3.7 RC3-3

**Comment by ikkentim** [comment]
Doesn't work for me either with SA-MP 0.3.7. When it I run SA-MP, I get a black screen but it doesn't crash(according to windows) and I need to manually shut it down. Single player runs fine however.

**Comment by Whitetigerswt** [comment]
Yeah, it seems to work in some of the older RC's but doesn't work in the final release. Foolish of me to think it would!

**Comment by Whitetigerswt** [comment]
I'm not having any problems using this in 0.3.7

**Comment by ikkentim** [comment]
Any way i can help?

It's not crashing, so I can't send a crash log or something

**Comment by Whitetigerswt** [comment]
is this still an issue?

**Comment by ESzn** [comment]
After looking in the deepest corners of my mind, I think I remember the problem being that I was using something that was outdated, I don't remember what though, since this was a lot of time ago. It was solved in the end, at least for me.
