### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by JustMe77** [Whitetigerswt/gtasa_crashfix#26]
Hey, I just got Windows 10 yesterday and I noticed my crashes.asi is not working anymore. I tried to reinstall it and it didn't helped. Friends told me I should try it with the .exe but it also didn't help me.

Do I need something else except the asiloader and the asi file ? If yes, send me a link please.

**Comment by Whitetigerswt** [comment]
I have windows 10 and it is working fine for me. Are you sure this is not another problem?

**Comment by JustMe77** [comment]
What kind of another problem? I got all the requirements you mentioned in the Info. I have seen someone else having a problem with Windows 10 but he solved it with downloading some Microsoft Visual Studio. I did the same but it didnt helped me..

And your Anticheat is not working too. SAMP is just not starting..
