### ISSUE TITLE
Crashes.asi not loading in SA-MP

### ISSUE THREAD

**Issue by Bradda** [Whitetigerswt/gtasa_crashfix#27]
I don't know how but this day your .asi file isn't working for me anymore. SA-MP just loads in a black screen, and loads, and loads... I can only stop the running gta_sa.exe with Ctrl Alt Delete -> Sign Out.

Running on Windows 10, please help me out, this modification improves my gameplay a lot

**Comment by Whitetigerswt** [comment]
That's odd. It is probably something on your computer that you've done
recently that is causing it though. This mod has not been changed in
months. Can you think of anything you've done that would cause it?

**Comment by Bradda** [comment]
Hi,

That's odd indeed. I have tried everything that's possible; reinstalling GTA SA, SA-MP, even renamed the GTA SA folder. I have no clue what I have done the past day that is causing this, maybe a file is missing? I don't know.

**Comment by Bradda** [comment]
UPDATE:

Hi again, well the thing is; I gave it a try to install this again and, (now here comes the funny part), I have edited and saved the crashes.cfg, but when I tried to save the text file, I had to save it to my desktop in order to replace it in the GTA SA folder, and now it works perfectly, lol.

**Comment by Bradda** [comment]
Okay, I have found a very strange bug in this modification:

When I am launching SA-MP, while frame limiter is turned **ON**, the mod won't load; which means the game won't load as well.

When I am launching SINGLEPLAYER, while frame limiter is turned **ON**, the mod DOES load; which means the game loads and runs fine.

Now, I have discovered that when I turn my frame limiter **OFF** in SINGLEPLAYER, I exit the game from SINGLEPLAYER, and I enter SA-MP, with frame limiter **OFF**, the game loads and runs!

Whitetigerswt, you gotta' fix this man.

**Comment by Bradda** [comment]
You still here? lol

**Comment by Whitetigerswt** [comment]
That's interesting. I'll see if I can reproduce that on my computer. I'll get back to you

**Comment by Bradda** [comment]
Have you reproduced my issue, @Whitetigerswt ?
