### ISSUE TITLE
Crashes.asi failed to load

### ISSUE THREAD

**Issue by Bradda** [Whitetigerswt/gtasa_crashfix#32]
Hello Whitetigerswt,

Today I re-installed Windows 10 for private reasons, however I re-installed GTA SA and all... and decided to install this mod again. I've got Silent's ASI Loader as well, but now I get this
![capture](https://cloud.githubusercontent.com/assets/17316532/14941927/155ceec2-0fae-11e6-9cbd-51c851480681.PNG)

Am I missing something? I have installed Microsoft Visual C++ 2015, restarted PC, nothing works.

**Comment by Whitetigerswt** [comment]
did you install using the installer file or just copy the .asi? try using this: https://github.com/Whitetigerswt/gtasa_crashfix/releases/download/v2.4/crashes-v2.4.exe

**Comment by Bradda** [comment]
Yes, I did, still same problem

**Comment by Bradda** [comment]
Am I missing an important file on my computer for this to work?

**Comment by Whitetigerswt** [comment]
I'm not sure what you're missing. Do other asi scripts load correctly?

**Comment by Bradda** [comment]
Yes, I have CLEO.asi as well and it works perfectly fine.

**Comment by Bradda** [comment]
@Whitetigerswt 

When I try opening CrashSender1402.exe in my GTA SA folder, this appears to happen

![capture](https://cloud.githubusercontent.com/assets/17316532/15150527/e3a7ea72-16cd-11e6-8ece-d896c432eca9.PNG)

**Comment by Whitetigerswt** [comment]
You're not meant to open that executable by itself, but you can fix that issue by installing Microsoft visual c++ 2010 (no newer versions) (be sure to install the 32 bit version or sometimes it's called x86)

**Comment by Bradda** [comment]
@Whitetigerswt 

I will try that, thanks. I will inform you what happens afterwards.

**Comment by Bradda** [comment]
@Whitetigerswt 

Thank you! It works. Thanks for your help.
