### ISSUE TITLE
Brightness issue

### ISSUE THREAD

**Issue by IvanTheNotSoTerrible** [Whitetigerswt/gtasa_crashfix#37]
Hi, I installed everything correctly and I've set my brightness to -1 in the configuration file, yet my brightness is still too high in game. Once I press esc twice, the problem is fixed and it returns to the normal brightness.
When I press alt+tab, after fixing the problem using esc, the screen brightness becomes high then returns to normal.
I also tried to manually change the brightness in game then restart it, but I still have the same problem.
Other than that, the mod is great, I haven't crashed or frozen at all since I've installed it.
One more thing, do I need all these other files? Or shall I only keep the "Release" file?
Thanks!

**Comment by Matz47** [comment]
Use -4

**Comment by Whitetigerswt** [comment]
I believe this is a bug with GTA:SA. The brightness is only applied as soon as you pause for the first time.

**Comment by DooMl** [comment]
Same here, can you add a parameter for brightness to be completely disabled?
-using Windows 8
