### ISSUE TITLE
Microsoft c runtime library error

### ISSUE THREAD

**Issue by rajasr93** [Whitetigerswt/gtasa_crashfix#38]
I have install Microsoft c++ redistributable but it still askes me for msvcp100 and msvcr100 dll files help me pls

**Comment by Whitetigerswt** [comment]
There are different versions of the Microsoft C runtime library. The one that is required for this is the VC++ 2010 redistributable. You can find that here: https://www.microsoft.com/en-us/download/details.aspx?id=5555

Make sure you installed this one and not one from a different year (2013, 2016).
