### ISSUE TITLE
Swim problem

### ISSUE THREAD

**Issue by mehrangta** [Whitetigerswt/gtasa_crashfix#39]
Hello, the player cannot swim fluently with this mod.

**Comment by Whitetigerswt** [comment]
You sure that's related to this mod? You cannot swim in this game very well if your FPS is over 30.

**Comment by mehrangta** [comment]
My fps is about 250-300 using fraps. I can create a video with and without this mod.

**Comment by Whitetigerswt** [comment]
What is the difference in swimming if you did that? Just the speed?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
