### ISSUE TITLE
Weird sync with 0.3.DL

### ISSUE THREAD

**Issue by TwisT3RHU** [Whitetigerswt/gtasa_crashfix#41]
Players are just sliding on the map on 0.3.DL while using this crashfix.

**Comment by Whitetigerswt** [comment]
Players who use this slide around for others or others appear to slide around for the person using this?

**Comment by TwisT3RHU** [comment]
The latter. Everyone slides for me while using this.

**Comment by Whitetigerswt** [comment]
Check #42 for updates on this issue.
