### ISSUE TITLE
crashes.asi crash with skygfx

### ISSUE THREAD

**Issue by nickgers** [Whitetigerswt/gtasa_crashfix#49]
Not really an issue but is there any fix or way round this incompatibility? Can't seem to get either to work together.

**Comment by Whitetigerswt** [comment]
No idea, I've never used this mod. It's probably because some of the graphic changes from Stream INI extender.

**Comment by nickgers** [comment]
forgot to mention only the latest version does not work with it. 2.4 worked fine with it

**Comment by Whitetigerswt** [comment]
Please try this release: https://github.com/Whitetigerswt/gtasa_crashfix/releases/tag/v2.51

**Comment by nickgers** [comment]
Working perfectly. Thanks a lot man
