### ISSUE TITLE
Is there godmode in crashes.asi?

### ISSUE THREAD

**Issue by harrysanchezs** [Whitetigerswt/gtasa_crashfix#50]
How're u doing?
Above all I wanna thank you for this amazing plugin which's supported low perfomance PCs so far.
I'm appealing as a regular player of russian SA:MP project, it got ~5k players on the average. So the project's developers've prohibited your plugin recently according to "presence of godmode".
Mainly they say about player falling godmode: when a player falls from the high and doesn't get a damage, it happens not always but it does. Also the plugin blocks some shots at players' firefight, it happens too rarely but anyway.
What is your opinion about this?

**Comment by zawadiaka0000** [comment]
I'm having exactly the same problem. Then I tried to use the previous version and that one doesn't even load.

**Comment by Whitetigerswt** [comment]
There's some code to prevent climb bug which causes some other issues when falling. There's always been issues in the engine with fall damage at >60 fps tho, but with the changes to climb bug it's detectable by the scripters.

**Comment by Whitetigerswt** [comment]
I haven't had a chance to look into the issues with 2.5 very much, but I wouldn't use it.

**Comment by Whitetigerswt** [comment]
Please try this release: https://github.com/Whitetigerswt/gtasa_crashfix/releases/tag/v2.51

**Comment by harrysanchezs** [comment]
> Please try this release: https://github.com/Whitetigerswt/gtasa_crashfix/releases/tag/v2.51

Wow, you're very responsive. That's a great work. I thank you so much.
I'll contact the developers very soon and show this version of the plugin.
Your plugin is one of a kind. I don't know other plugins that can boost your FPS, save you from crashes, speed game's loading up, fix compatibility on Windows 10 and just fix some graphic details in SA:MP. I even don't know pack of .cs and .asi files that can do the same. That's why I like and many players need your plugin. Keep going bro, we appreciate it.
