### ISSUE TITLE
Black circle under character after crashes install.

### ISSUE THREAD

**Issue by Lafayette1975** [Whitetigerswt/gtasa_crashfix#60]
After I have installed crashes I noticed that I have a little black circle under my character that looks like a shadow and which moves with my character when I move. I am on High Graphics. This normally happens when you are on Low Graphics without crashes.

How can I get my character to look normal again without the circle under its feet?

**Comment by Whitetigerswt** [comment]
There's an option in crashes.cfg that controls this, I believe it's "shadows 0" by default. Try changing it to "shadows 1"
