### ISSUE TITLE
A small suggestion

### ISSUE THREAD

**Issue by gabrielz07** [Whitetigerswt/gtasa_crashfix#61]
I was looking around what mod in my library was causing it and I found actually that this mod forces to have the Pause Menu defaulted to the Load Game menu selection, I think this is irrelevant for SAMP for example and I would like to know if it can be changed back to the original default mode of having the normal usual options first, instead of having to back all the way to the to the main menu for changing anything or seeing the map, for what I saw it was introduced with the addition of quickload.cpp in 1.8 beta.
Perhaps removing this feature or at least having the option to disable could be a good thing. Thanks

**Comment by Whitetigerswt** [comment]
When you pause in SA-MP, you see the load game menu?

**Comment by gabrielz07** [comment]
> When you pause in SA-MP, you see the load game menu?

Exactly, I experimented that behavior in both PCs I have, I checked out the differents versions of this mod and the issue clearly starts in the introduction of the version 1.8 beta and all the posterior versions, previous versions of the mod doesn't have this problem.

**Comment by Whitetigerswt** [comment]
See if this is working in https://github.com/Whitetigerswt/gtasa_crashfix/releases/tag/v2.52

When I run the game in sa-mp or single player, i don't get these menu changes your talking about so hard for me to know if this is a fix or not.

**Comment by gabrielz07** [comment]
> See if this is working in https://github.com/Whitetigerswt/gtasa_crashfix/releases/tag/v2.52
> 
> When I run the game in sa-mp or single player, i don't get these menu changes your talking about so hard for me to know if this is a fix or not.

It's fixed now, thanks a lot
