### ISSUE TITLE
SAMPCAC Conflict

### ISSUE THREAD

**Issue by ghost** [Whitetigerswt/gtasa_crashfix#72]
Hey, I really liked your plugin. Bug can you add support in working with SAMPCAC?

**Comment by Whitetigerswt** [comment]
You should ask them to implement support in sampcac.

**Comment by ghost** [comment]
The author has stopped the development of the anti-cheat.

**Comment by Whitetigerswt** [comment]
If it doesn't work then the developer has made strides to specifically block it. It's probably best to block it since the high fps can be considered a cheat.

________________________________
