### ISSUE TITLE
VirusTotal is not always reliable

### ISSUE THREAD

**Issue by Is0kaze** [Whitetigerswt/gtasa_crashfix#76]
https://www.virustotal.com/gui/file/ec29cbd8853f9ce8839704692b71b29076f374f30a18eee960288f6fddf95bbc/detection

**Comment by juanpenia** [comment]
nah

**Comment by Whitetigerswt** [comment]
I wish I knew why it did that, maybe because I'm doing memory hacking anti viruses have a problem. But all the code is on this Github, I don't have anything to hide.

Feel free to compile yourself if you don't trust me
